language: php

sudo: false

php:
  - 7.3
  - 8.0
  - 8.1

before_script:
  - composer install

script:
  - vendor/bin/phpunit --coverage-clover=coverage.xml tests/
  
after_success:
  - bash <(curl -s https://codecov.io/bash)

notifications:
  email: false
