version: 2

jobs:
  build:
    docker:
      - image: circleci/php:7.4
    steps:
      - checkout
      - run: sudo apt update
      - run: sudo docker-php-ext-install zip
      - run: composer install -n --prefer-dist
      - run: ./vendor/bin/phpunit tests
      - run: bash <(curl -s https://codecov.io/bash)
